/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as wmdbGovernorSol from "./WMDBGovernor.sol";
export type { wmdbGovernorSol };
export type { TimeLock } from "./TimeLock";
export type { WMDB } from "./WMDB";
export type { WMDBToken } from "./WMDBToken";
