/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GovernanceToken } from "./GovernanceToken";
export type { TimeLock } from "./TimeLock";
export type { WMDB } from "./WMDB";
export type { WMDBGovernor } from "./WMDBGovernor";
export type { WMDBToken } from "./WMDBToken";
