/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GovernanceToken__factory } from "./GovernanceToken__factory";
export { TimeLock__factory } from "./TimeLock__factory";
export { WMDB__factory } from "./WMDB__factory";
export { WMDBGovernor__factory } from "./WMDBGovernor__factory";
export { WMDBToken__factory } from "./WMDBToken__factory";
