/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as wmdbGovernorSol from "./WMDBGovernor.sol";
export { TimeLock__factory } from "./TimeLock__factory";
export { WMDB__factory } from "./WMDB__factory";
export { WMDBToken__factory } from "./WMDBToken__factory";
