/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MyGovernor__factory } from "./MyGovernor__factory";
export { WMDBGovernor__factory } from "./WMDBGovernor__factory";
